apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/venkatvar/javaapp-1-8420:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/venkatvar/javaapp-1-8420:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: javaapp-1-8420
        chartPath: charts/javaapp-1-8420
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/venkatvar/javaapp-1-8420"
          image.tag: "{{.DIGEST_HEX}}"
